name: fuerzauy
description: Proyecto Fuerza Uruguay

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  firebase_auth: ^0.15.5+3
  google_sign_in: ^4.4.1
  firebase: ^7.3.0
  firebase_storage: ^3.1.5
  cloud_firestore: ^0.13.5
  image_picker: ^0.6.5
  fluttertoast: ^3.1.0
  uuid: 2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
